### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by Sanchita1304** [danger-ahead/simple_chips_input#3]
Hi, I would like to give some UI design for this app using Figma. 
Figma is a designing tool where web and app designs can be created.

**Comment by danger-ahead** [comment]
> Hi, I would like to give some UI design for this app using Figma. Figma is a designing tool where web and app designs can be created.

I believe the UI of this package is customizable as per the developer. It doesn't need any UI design. The UI in the screenshot are just examples. Is that what you meant?

**Comment by Sanchita1304** [comment]
yes

**Comment by danger-ahead** [comment]
> yes

If you have any other idea regarding the project, let me know! Closing this as of now.
Thanks for your time!
